localization:

  image: ubuntu:jammy

  only:
    - schedules

  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y qt6-base-dev qt6-l10n-tools openssh-client git wget
    - qtchooser -install qt6 $(which qmake6)
    - export QT_SELECT=qt6
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "${SSH_PUBLIC_KEY}" >> ~/.ssh/id_rsa.pub
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git clone git@gitlab.com:luspi/photoqt-lang.git && cd photoqt-lang
    - lupdate -no-obsolete ../qml/ ../cplusplus/ -ts photoqt-qt6.ts
    - git add photoqt-qt6.ts
    - git diff-index --quiet HEAD || git commit -m "updating translation source files from CI - Qt6 version"
    - git push

